#! /usr/bin/env python
"""
This script plots uv-coverage.

Written by Shifan Zuo.
"""

import os
import sys
import optparse
import numpy as n
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import h5py


o = optparse.OptionParser()
o.set_usage('%s [options] *.hdf5' % sys.argv[0].split('/')[-1].strip())
o.set_description(__doc__)
o.add_option('-g', '--grid', dest='grid', action='store_true',
    help='Add grid if Tue.')
o.add_option('-o', '--outfile', dest='outfile',
    help='If provided, will save the figure to the specified file.')
opts, args = o.parse_args(sys.argv[1:])


for cnt, filename in enumerate(args):
    print filename
    cnt = 0
    if opts.outfile is None:
        outfile = filename.replace('.hdf5', '.png')
    else:
        outfile = opts.outfile
    if os.path.exists(outfile):
        print 'Output file exists... skipping.'
        continue
    # # Gather data
    # d, kwds = a.img.from_fits(filename)
    # print d.shape
    # print kwds
    # print '-----------------------------------------------------------'
    with h5py.File(filename, 'r') as f:
        uvw = f['uvw'][...]
    u = uvw[:, 0]
    v = uvw[:, 1]

    fig = plt.figure()
    fig.add_subplot(111,aspect='equal')
    plt.scatter(u, v, s=0.2, c='k', marker='o')
    if opts.grid:
        plt.axhline(0, color='k', linestyle='--')
        plt.axvline(0, color='k', linestyle='--')
    plt.xlabel('$u \ / \ \lambda$')
    plt.ylabel('$v \ / \ \lambda$')
    plt.savefig(outfile)
